pipeline:
  build:
    image: plugins/kaniko
    settings:
      repo: $CI_REPO
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: master
