---
matrix:
  ARCH:
    - amd64
    - arm64

steps:
  - name: build
    image: woodpeckerci/plugin-kaniko
    backend_options:
      kubernetes:
        nodeSelector:
          kubernetes.io/arch: ${ARCH}
        tolerations:
          - key: arch
            operator: Equal
            value: ${ARCH}
            effect: NoSchedule
    settings:
      repo: ${CI_REPO}
      registry: harbor.codemowers.eu
      tags: latest-${ARCH}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      - branch: master
